### ISSUE TITLE
Install ImageMagick-7 and an updated php-wrapper for IM7

### ISSUE THREAD

**Issue by mmattel** [owncloud-docker/php#46]
Colleagues, I would like to highlight a document in docs which guides you tru the installation of ImageMagic 7. It also explains the reason why doing so is a good thing. This could easily be implemented in our docker default, we do similar things for the libsmbclient wrapper. Using IM7 is benifitial for QNAP and other systems which use our docker environment.

https://doc.owncloud.com/server/admin_manual/installation/manual_installation/manual_imagick7.html (Install an Updated ImageMagick Version)

@jnweiger @xoxys @wkloucek @EParzefall

**Comment by xoxys** [comment]
@jnweiger @pako81 Cloud you investigate https://central.owncloud.org/t/latest-official-docker-image-crashes/44887? If we can't find a short-term solution. We should temp. revert this change.
